# Generated by Django 3.1.4 on 2020-12-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='icon',
            field=models.ImageField(blank=True, upload_to='sources_icons/'),
        ),
    ]
